### DISCUSSION TITLE
Masonry layout for galleries

### DISCUSSION THREAD

**Discussion by 3muchfun** [GetPublii/Publii#1387] [Help] [answered]
Hi, @candidexmedia,

I adapted your css from https://gist.github.com/candidexmedia/374a7ae87cc4d2fbc622ca3a50773106 , and it works pretty well, except one thing: I chose a wide gallery layout while creating the gallery in the post, but the output in preview mode is the standard small layout.
![Bildschirmfoto 2024-02-21 um 11 43 42](https://github.com/GetPublii/Publii/assets/17292904/96b5b5fb-cb2a-4337-ba79-99db39d812d7)

Output:
![Bildschirmfoto 2024-02-21 um 11 46 21](https://github.com/GetPublii/Publii/assets/17292904/b08ac9f0-b40f-46e5-b6da-c2e7a13e7abb)

Output if I change to 'your' masonry layout:
![Bildschirmfoto 2024-02-21 um 11 45 13](https://github.com/GetPublii/Publii/assets/17292904/df6ab879-ffb2-45a6-84dd-0af1c5eb0073)

Thanks in advance, Michael

**Comment by candidexmedia** [comment]
Hi! Do you have a link to a live page that can be inspected?

**Reply by 3muchfun** [reply]
not at the moment, I will provide one next week

**Reply by 3muchfun** [reply]
@candidexmedia , as requested:
Both sites have the same gallery layout, 3 columns, wide, as mentioned above.
normal, wide gallery: https://fluegge.net/galleries/black-and-white/
cloned website with the CSS changes, also wide: https://fluegge.net/galleries2/black-and-white/

**Reply by candidexmedia** [reply, marked as answer]
Thanks @3muchfun !

Replace:

```css
@media all and (min-width:56.25em) {
  .gallery-wrapper--wide .gallery {
    width:calc(100% + .5666666667rem)
  }
}
```

With:

```css
@media all and (min-width:56.25em) {
  .gallery-wrapper--wide {
    display:flex;
    justify-content:center;
    margin-left:calc(-50vw + 50%);
    margin-right:calc(-50vw + 50%)
  }
  .gallery-wrapper--wide .gallery {
    padding:0 var(--page-margin);
    max-width:var(--page-width)
  }
}
```


I've also [updated my gist](https://gist.github.com/candidexmedia/374a7ae87cc4d2fbc622ca3a50773106/revisions#diff-b187f5bae0855fc0896faefbe5b0262ab6750d7d512aceb256cfd18409911f5c). Thanks for flagging!
