### DISCUSSION TITLE
Help with transition from GitLab to Git Repository method

### DISCUSSION THREAD

**Discussion by plasmidone** [GetPublii/Publii#1415] [Help]
Hi everyone. I am able to sync just fine with GitLab server using Publii 0.40.3.

However, when I try to use Publii 0.45.0 and setup Git Repository because GitLab will be deprecated, I am getting the following error message:

Error! Application was able to connect with your server but was unable to store files.

I have looked at previous forum posts but the answer is that a new version of Publii (version 0.41...) would fix the same error, but I am trying to use 0.45 so it's confusing. I have looked at the Publii online support articles but they are either outdated (explaining how to setup the deprecated method...) or do not explain the fields of the Git Repository setup in details to make sure setting up the new method does not lead to errors. Several of the fields are different. For exemple, it is not clear whether the "Repository URL" field should include https:// or not.
I have tried with both and get error messages regardless.

I am not sure what to do now since my old setup is still able to sync just fine. I have tried creating a new API token for Publii 0.45.0, but I still get the same error. Any help would be appreciated.

**Comment by dziudek** [comment]
Hi,

Definitely something is wrong with your settings - the repository URL should be like:

https://gitlab.com/publii-test/publii-test2024.git

Also please remember to give proper permissions for the token nad use it in the password field

And most important - please remember to add to the Tools -> File Manager -> root-files .gitlab-ci.yml file which contains the following:

```
pages:
  stage: deploy
  script:
    - mkdir .public
    - cp -r * .public
    - mv .public public
  artifacts:
    paths:
      - public
  only:
    - main
```

Of course I assume that you are usin `main` as a branch name :)

**Reply by plasmidone** [reply]
Like in the documentation tutorial, my .gitlab-ci.yml contains the following:

```
image: alpine:latest
pages:
  stage: deploy
  script:
  - echo 'Nothing to do...'
  artifacts:
    paths:
    - public/
  only:
  - main
```

Is the below page out of date and I should use the code you provided instead?
https://getpublii.com/docs/host-static-website-gitlab-pages.html
