### DISCUSSION TITLE
Can't upload files to Gitlab. Please Help

### DISCUSSION THREAD

**Discussion by sloppy-ninja** [GetPublii/Publii#1464] [Help]
I have a private repository with gitlab pages enabled. There are these files: .gitlab-ci.yml and public folder with html files.

Since i have a private repository, I need publii to upload all the files from program to gitlab public folder. I don't know how to do it and even when I just try to sync my site with gitlab from publii I get an error:
`PushRejectError: Push rejected because it was not a simple fast-forward. Use force: true" to override.`

Here is my yml config:
```
image: alpine:latest 
pages:
  stage: deploy
  script:
  - echo 'Nothing to do...'
  artifacts:
    paths:
    - public/
  only:
  - main
```
  
  I will be glad if you help me!
