### DISCUSSION TITLE
How to make header absolute

### DISCUSSION THREAD

**Discussion by nootkan** [GetPublii/Publii#1544] [Help] [answered]
I am new to publii and need some guidance.  Looked over docs and other posts here but can't find what I am looking to do.  I need the header to stay at the top at all times even when scrolling to the bottom.  Using the default theme.

**Comment by candidexmedia** [comment]
Which theme are you using?

Generally speaking, the hiding of the header is a Javascript thing that the Publii devs added. It's essentially like a switch which toggles the CSS class `.header.is-hidden` to `.header.is-visible`.

If you're comfortable with JavaScript, feel free to nip it at the root in the `main.js`.

Otherwise, the simplest way to address it on the theme I typically use (Mercury) is to just tweak the CSS so that both rules are the same/similar.

To hide the top navigation menu after you scroll, add this CSS rule:

```css
.header.is-visible {  
  opacity: 0;
}
```

To make the top navigation menu visible at all times, even when scrolling, add this CSS rule:

```css
.header.is-hidden {
  -webkit-box-shadow:0 3px 10px 0 rgba(0,0,0,.06);
  box-shadow:0 3px 10px 0 rgba(0,0,0,.06);
  opacity:1;
  position:fixed;
  -webkit-transform:translate(0,0);
  transform:translate(0,0);
  -webkit-transition:all .3s ease-out;
  transition:all .3s ease-out;
  top:0;
}
```


You can make CSS edits in the GUI, under Tools, or by [editing your theme files](https://github.com/GetPublii/Publii/discussions/1412#discussioncomment-8696413).

**Comment by nootkan** [comment]
Thanks for the reply but I haven't figured out how to get the menu to show in the header over the hero image yet just the logo.

I also forgot to mention I used this css to get close to what I need:
`.top.is-visible `{background-color:transparent;box-shadow:none;}`

The theme is the default one that comes with the new installation (Simple v.2.8.3.0).
  
Currently when I scroll down I see the logo/hero image/content like I want but as soon as I start to scroll back up the logo/header appears.

See screenshots below of my homepage with hero image/logo and then the content below hero image and the content once I start to scroll back up the page to see what I mean.  
 
![ScreenHunter_614 Jun  17 14 17](https://github.com/GetPublii/Publii/assets/744769/564ba137-776e-47e5-a867-d33161703ef0)


![ScreenHunter_616 Jun  17 14 31](https://github.com/GetPublii/Publii/assets/744769/608ac104-1fcd-422d-8ec3-67a37648672b)


![ScreenHunter_615 Jun  17 14 29](https://github.com/GetPublii/Publii/assets/744769/f561134f-671e-43cf-8728-7a2de73e9df9)

**Reply by candidexmedia** [reply, marked as answer]
# Hide header

Gotcha! Add the following to `.top.is-visible`:

```css
.top.is-visible {  
  opacity: 0;
}
```

Demo (also in [video form](https://i.imgur.com/9KQApsi.mp4)):

![9KQApsi - Imgur](https://github.com/GetPublii/Publii/assets/55474996/b650b0dc-20e7-4f7f-bf00-bd138f485c02)


# Menu

> I haven't figured out how to get the menu to show in the header over the hero image yet just the logo.

Go to the Menus tab in the GUI, create a menu, add your menu items (you can map them to an existing page, tag, author, etc.), and make sure to assign the menu to your Main menu:

![image](https://github.com/GetPublii/Publii/assets/55474996/65370f9f-1d42-4e53-9368-40dc859645be)
