### DISCUSSION TITLE
Please: dark mode for documentation themes

### DISCUSSION THREAD

**Discussion by johnnyitd** [GetPublii/Publii#1838] [Ideas]
Guys, can we please get dark mode for ProDocs or Documentation? 

Changelog is kinda cool, but is very fat with a lot of wasted space.

**Comment by candidexmedia** [comment]
Update: I figured out how to create a toggle for the Simple theme, and made a gist: https://gist.github.com/candidexmedia/e1dc9fb0ce85eddeadc236d6b21e25cd

Try it out with your theme. 😊

**Comment by gpsblues** [comment]
Hi @johnnyitd,

you could try a basic color inversion.
This CSS mimics, in a less sophisticated way, how some browsers offer a manual dark mode.

```CSS
/* Color inversion */
html {
    filter: invert(100%) hue-rotate(180deg);
}
/* Re-inversion for images, svg, videos */
html img,
html svg, /* svg is optional */
html video {
    filter: invert(100%) hue-rotate(180deg);
}
```
It's a compromise, but if your site has a favorable color scheme, it might work without further effort.
A good result isn't always guaranteed, but it's definitely worth a try.

**Heads up! Your designer might stop talking to you** :) 
This technique could also be applied to the dark/light toggle button.
