### DISCUSSION TITLE
[Bug report] Unable to upload .github/workflows folder for custom actions

### DISCUSSION THREAD

**Discussion by Kikketer** [GetPublii/Publii#2025] [Bug Report]
### Operating system

macOS 15.3

### Publii version

Version 0.46.3 (0.46.3)

### Issue type

Application

### Bug description

I'd like to use github actions on the publii github pages site.  However currently Publii wipes the entire repo every time it syncs which means the .github/workflows is deleted each time.  The actions are needed for other portions of my site that include pages/applications that aren't handled by Publii.

Issues:

1. Publii wipes the entire repo so even if I attempt to put something on the repo (regardless of what it is) it's wiped out completely every time Publii syncs
2. Publii does not allow me to put `.`s in folder names, reporting an error on sync claiming a `404`
3. Github does not allow automatic running of github actions on branches when there's no .github/workflows file in that branch

The steps I attempted to work around this (and are pretty close):

1. Create a separate branch `publii` that Publii publishes to
2. On the main branch have the .github/workflows folder with my actions in it
3. In the main version of the workflows, I have it check out the `publii` branch, save it to a folder then publish that folder via github actions (instead of running the default static site generation where it's compiling jekkyl and such, unnecessary)

Unfortunately due to the issues above this still does not work automatically.  It does work if I have the `workflow_dispatch` on that action which I can trigger manually after syncing up Publii

### Steps to reproduce

1. Use github pages
2. Add `.github/workflows/some-action.yml` to the `/inputs/root-files`
3. Attempt to sync the Publii page

### Relevant log output

```shell
[Sun, 16 Feb 2025 00:04:01 GMT] CREATE BLOB: /[redacted]/[redacted]/[redacted]/Publii/sites/chris-weed/output/.github/workflows/some-action.yml
[Sun, 16 Feb 2025 00:04:01 GMT] CREATED BLOB: /[redacted]/[redacted]/[redacted]/Publii/sites/chris-weed/output/.github/workflows/some-action.yml - ce796b9ede2545984b9ec9cf9cd2648d245a9593
[Sun, 16 Feb 2025 00:04:01 GMT] (i) TRIED AGAIN: (api) => api.gitdata.createTree - undefined
[Sun, 16 Feb 2025 00:04:01 GMT] (i) TRIED AGAIN FAIL: (api) => api.gitdata.createTree - undefined
[Sun, 16 Feb 2025 00:04:01 GMT] ERROR: {"code":404,"status":"Not Found","message":"{\"message\":\"Not Found\",\"documentation_url\":\"https://docs.github.com/rest/git/trees#create-a-tree\",\"status\":\"404\"}"}
```

**Comment by bjazmoore** [comment]
Publii will not wipe a repository and reupload the entire site under normal conditions.  Publii creates a file that contains a hashed version of each file.  If the hash on future synchronizations matched the hash in the hash file the existing file is not uploaded again.  It is likely that your GitHub actions are touching each file causing every file to be invalidated and therefore resynchronized. 

I have not tested it, but I also suspect that the synchronization process will remove any file from the repository that is not in the local copy of the site generated by Publii.

Perhaps there is a way to do this with two different repositories.  One which Publii synchronizes to and the second which is your real website.  You could cause your first github action to copy the files from the Publii destination to your real website and then apply your other actions.

**Reply by Kikketer** [reply]
Ok yeah I think I'm seeing that it's not wiping the entire repo but it is destroying the workflow folder. This is likely due to the fact that it's not part of the hashed files that Publii is responsible for, and knowing that it will wipe anything that it didn't account for keeps me in a little bit of a "stay in your branch" fear state.

The copy process is exactly what I do but in a branch form vs two repositories. The static page build simply checks out the branch and copies it over during the build.

```
name: Deploy static content to Pages

on:
  push:
    branches: ['publii', 'main']
  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: "pages"
  cancel-in-progress: false

jobs:
  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    steps:
---- checkout the main branch
      - name: Checkout main branch
        uses: actions/checkout@v4
        with:
          ref: main
---- checkout the generated publii branch into a publii-content folder
      - name: Checkout publii branch
        uses: actions/checkout@v4
        with:
          ref: publii
          path: publii-content
      - name: Setup Pages
        uses: actions/configure-pages@v5
---- publish the publii content
      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: 'publii-content'
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
```

The action above will publish the publii branch to github pages. This is needed because there's no workflow folder in the publii branch (and there can't be since it wipes it out and refuses to let any dot folder be part of the static content).
