### DISCUSSION TITLE
Disable darken image on hover

### DISCUSSION THREAD

**Discussion by owennewo-dev** [GetPublii/Publii#2228] [Help]
How can I disable the effect where when you hover your mouse over an image it darkens the image slightly?

Thank you in advance.

**Comment by owennewo-dev** [comment]
Update:

I solved my problem by changing `opacity: 1` to `opacity: 0`

`main.css line 2164`
```css
.gallery__item a:hover::after {
  opacity: 0;
}
```
