### ISSUE TITLE
[Bug]: Issues with Mercury Theme variables

### ISSUE THREAD

**Issue by candideu** [GetPublii/Publii#1120]
### Operating system

Windows 10

### Publii version

0.39.1

### Bug description

I noted a few issues with the variables in the Mercury theme files. Some of them didn't take into account settings that would have been implemented by the user in the Theme Settings.

# Heading Weight

In `main.css`:

```css
h1,
h2,
h3,
h4,
h5,
h6 {
...
font-weight: var(--font-weight-normal);
  ...
}
```

Should be:
```css
h1,
h2,
h3,
h4,
h5,
h6 {
...
font-weight: var(--headings-weight);
  ...
}
```

# Heading Text Transform

In `main.css`:

The selector for the headings...

```css
h1,
h2,
h3,
h4,
h5,
h6 {
```

... should include `text-transform: var(--headings-transform);`
