### ISSUE TITLE
Comments via Fediverse / Mastodon with Publii

### ISSUE THREAD

**Issue by Krotosz6** [GetPublii/Publii#1301]
### Feature Description

I think I have a nice solution to visible a in blog post in Publii comments via Fediverse / Mastodon. I think it could be a nice booster to implement it Publli in one of the plugin comments.

https://carlschwan.eu/2020/12/29/adding-comments-to-your-static-blog-with-mastodon/

For now I have put pure code in custom HTML.

Could You help mi to put those example parameters to blog post:
```

comments:
  host: floss.social
  username: carlschwan
  id: 109774012599031406
```
