### ISSUE TITLE
Allow for multiple languages websites

### ISSUE THREAD

**Issue by YoavRheims** [GetPublii/Publii#60]
Add options for multiple languages websites and native hreflang support for the sitemap.

**Comment by YoavRheims** [comment]
No problem, priorities first 👍

**Comment by robokow** [comment]
Actually, there may be a really easy workaround. 

In the SEO box in a post place a new box called "Other language". The idea is that I just add a url in that box and the language. 

Publli would then add a new line in the head of that post like `<link rel="alternate" hreflang="fr" href="https://given.url/in-the-box">` 

Like this I can connect multiple language-sites on the same domain.

**Comment by dziudek** [comment]
@robokow - in fact if you need - you can achieve it by yourself using custom post settings in your theme: https://getpublii.com/dev/theme-settings-api/ :)

**Comment by nekohayo** [comment]
In an "ideal" world, instead of the user having to manage each page's alternate URLs manually, Publii could handle the notion of posts/pages' alternate language versions like [Polylang](https://wordpress.org/plugins/polylang/) does, including a "language switcher" navbar item (and a switcher inside the editing interface too), and also being able to configure how the distinction between languages is made in the website's URLs:
* no distinction at all, everything sits in the root, just the post names and metadata being different, and I guess the feeds and posts listings showing language-specific versions (when available, or not at all)
* language as a subdirectory (ex: foo.com/fr/ze_post)
* language as a subdomain (ex: fr.foo.com/ze_post)
* completely separate domain names

There is also value in allowing to have a website where _UI elements_ (menus, categories, tags, headers / footers / front page / sidebars) can be translated and the _content_ (posts) left untranslated but displayed in all languages; one thing that is annoying with Polylang and many other multilingual systems is that they force you to have multilingual versions of the content "or they won't display the non-translated posts"; this is fine and desireable for corporate websites, but impractical for personal blogs that write "alternatingly" in different languages (not necessarily translated) but want a translated UI.

I know this is not the no1 priority, just sharing my wishes and some caveats for your future consideration ;) unfortunately, since I'm in an officially bilingual country, until there's support for multilingual websites, I can only use Publii for simple personal blogs, and cannot yet recommend it for businesses wanting to build their website.

**Comment by JOduMonT** [comment]
Since the begin this multi language option is planned by Publii Team, but then they always push it back, it is sad, Publii have many great advantage, but this one is killing my enthusiasm.

#### I'm sure by opening the code to the community the project would take off

Even the translation still lacking
![image](https://user-images.githubusercontent.com/5204724/104868283-873e8800-5975-11eb-8e69-9a7c590ef518.png)

**Comment by bobmitro** [comment]
> Even the translation still lacking

The theme translation is available, but you have to translate the theme yourself. https://getpublii.com/dev/translations-api/#translatingapubliitheme

**Comment by JOduMonT** [comment]
> lternate language versions like [Polylang](https://wordpress.org/plugins/polylang/) does

Polylang is great, but you can't have category and tag with the same name, such as a category called 
services in English and another services for French.

**Comment by nawarian** [comment]
Hey @YoavRheims I just did a PoC on my own project using configs and got it working.

I'm using the `technews` theme and got it working with the following changes:

**themes/technews/config.json**
```json
     "postConfig": [
+        {
+            "name": "altLink",
+            "label": "Alternate link",
+            "value": "",
+            "type": "text",
+            "group": "Alternate URL"
+        },
+        {
+            "name": "altLang",
+            "label": "Alternate link language",
+            "value": "",
+            "type": "text",
+            "group": "Alternate URL"
+        },
         {
```

**technews/partials/head.hbs**:
```html
+    {{#if @config.post.altLink}}
+        <link rel="alternate" hreflang="{{@config.post.altLang}}" href="{{@config.post.altLink}}" />
+    {{/if}}
```

And the new settings appear in the post settings sidebar:
<img width="424" alt="Screenshot 2022-01-11 at 16 06 44" src="https://user-images.githubusercontent.com/3905582/148967800-c9d50db8-78a0-45b8-96c8-398c5809055a.png">

Hope it helps.

Ref:
- https://getpublii.com/dev/text-input/
- https://getpublii.com/dev/theme-settings-api/

Cheers!

**Comment by candideu** [comment]
> Hey @YoavRheims I just did a PoC on my own project using configs and got it working.
> 
> I'm using the `technews` theme and got it working with the following changes:
> 
> **themes/technews/config.json**
> 
> ```json
>      "postConfig": [
> +        {
> +            "name": "altLink",
> +            "label": "Alternate link",
> +            "value": "",
> +            "type": "text",
> +            "group": "Alternate URL"
> +        },
> +        {
> +            "name": "altLang",
> +            "label": "Alternate link language",
> +            "value": "",
> +            "type": "text",
> +            "group": "Alternate URL"
> +        },
>          {
> ```
> 
> **technews/partials/head.hbs**:
> 
> ```
> +    {{#if @config.post.altLink}}
> +        <link rel="alternate" hreflang="{{@config.post.altLang}}" href="{{@config.post.altLink}}" />
> +    {{/if}}
> ```
> 
> And the new settings appear in the post settings sidebar: <img alt="Screenshot 2022-01-11 at 16 06 44" width="424" src="https://user-images.githubusercontent.com/3905582/148967800-c9d50db8-78a0-45b8-96c8-398c5809055a.png">
> 
> Hope it helps.
> 
> Ref:
> 
>     * https://getpublii.com/dev/text-input/
> 
>     * https://getpublii.com/dev/theme-settings-api/
> 
> 
> Cheers!

This fantastic, and a great short-term solution! Do you do the same for the post in the other language?

I hope that this year is the year that Publii offers multi-language support. Creating a separate site for each language is a little too cumbersome (especially when you're trying to write two articles simultaneously) -- unless Publii allows to have two instances of the app open at the same time.

Nawarian's method is amazing, but there's still the question of translating menus, tags, filtering through posts, etc.

**Comment by candideu** [comment]
Some projects that might be of interest/help for multilanguage: 

- https://github.com/Demivan/fluent-vue
- https://inlang.dev/

**Comment by candideu** [comment]
I've stumbled upon this video today: https://www.youtube.com/watch?v=5meQKQhGBZg
Although I don't understand the language, I was able to follow along and use the script to create a toolbar to automate translations in Publii. Although it isn't the manual translation solution we're looking for (especially in terms of SEO), it was a great short-term solution for me.

I essentially paste the following code into Tools > Custom HTML > Footer:

```html
<script src="https://translate.google.com/translate_a/element.js?cb=loadGoogleTranslate"></script>
<script>
    function loadGoogleTranslate() {
     new google.translate.TranslateElement ("google_element");
    }
</script>
```

I then pasted the following `div` where I wanted my widget to appear. I placed mine in the footer because it was less of a headache than the navbar, but it can be placed anywhere:

```html
<div id="google_element"></div>
```

And that's it! I made some additional CSS changes as well to remove Google branding, style the `select`, and remove the top bar:
```css
/* Remove google translate banner and branding */
.goog-te-banner-frame {
    display: none; /* Remove Google banner at the top */
}

body {
    position: unset !important; /* Remove space created by Google banner at the top */
}

.goog-logo-link, .goog-logo-link:link, .goog-logo-link:visited, .goog-logo-link:hover, .goog-logo-link:active {
    display: none; /* Remove Google logo below language switcher dropdown */
}
.goog-te-gadget {
    font-size: 0px !important;
    color: transparent !important;
    /* Remove "Powered by" text below language switcher dropdown */
}
.goog-te-combo, .goog-te-banner *, .goog-te-ftab *, .goog-te-menu *, .goog-te-menu2 *, .goog-te-balloon * {
    font-family: var(--body-font) !important; /* change font of language switcher dropdown to match site */
    color: var(--light) !important; /* make text in dropdown white */
}

select.goog-te-combo {
    padding-right: 1.2rem !important; /* reduce padding obscuring language name */
    padding: .2rem .8rem; /* make lang switcher thinner */
}

select.goog-te-combo option {
    background: var(--dark) !important; /* make dropdown dark */
}

@media all and (max-width:37.4375em) {
 #google_element {
     padding: 2rem .4rem; /* add padding when screen becomes smaller and footer items are stacked */
 }
```
